name: Deploy
on:
  pull_request:
    branches: [ "main" ]
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Demo VUEJS on VPS
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            cd /var/www/vuejs
            git clone git@github.com:JulieQuero/ApiPlateform_Movies.git
            cd ApiPlateform_Movies
            git pull
            npm install
            npm run build